// mot => définition courte, en français, une phrase.
export const LEXIQUE = {
  scrape: "La collecte : Prometheus se connecte au service et lit ses compteurs, à intervalle régulier.",
  liveness: "La sonde qui demande « ce processus est-il définitivement bloqué ? ». Son échec tue le conteneur.",
  readiness: "La sonde qui demande « cette instance peut-elle recevoir du trafic maintenant ? ». Son échec la retire du service, sans rien détruire.",
  'startup probe': "La sonde qui protège le démarrage : tant qu'elle n'a pas réussi une fois, la liveness et la readiness ne s'exécutent pas.",
  span: "Un segment d'une trace : une opération datée, avec un début et une fin, qui peut contenir d'autres segments.",
  exemplar: "Un lien attaché à un point de mesure, qui pointe vers une trace précise ayant produit ce point.",
  trace: "Le trajet complet d'une requête à travers un ou plusieurs services, reconstitué à partir de ses segments (les spans).",
  gauge: "Une jauge : une valeur qui monte et qui descend, comme une mémoire utilisée ou un nombre de connexions ouvertes.",
  counter: "Un compteur : une valeur qui ne fait qu'augmenter (ou repart à zéro au redémarrage), comme un nombre de requêtes reçues.",
  histogram: "Une série de compteurs par tranche de valeur, qui permet de calculer une médiane ou un p95 après coup.",
  throttling: "La bride imposée par le noyau à un conteneur qui a consommé tout son quota de temps processeur avant la fin de sa période.",
  bulkhead: "Une limite de concurrence : au-delà d'un certain nombre de requêtes en vol, les suivantes sont refusées tout de suite.",
  'rate limit': "Une limite de débit : au-delà d'un certain nombre de requêtes par seconde, les suivantes sont refusées, quelle que soit leur durée.",
  OOMKill: "La mise à mort d'un conteneur par le noyau Linux, quand sa mémoire dépasse la limite du cgroup. Le processus reçoit un SIGKILL, sans préavis.",
  'crash loop': "Un conteneur qui redémarre en boucle, chaque nouveau départ échouant à son tour pour la même raison.",
  autoscaler: "Le mécanisme qui ajoute ou retire des instances d'un service selon une métrique observée, comme le CPU moyen.",
  request: "La quantité de ressource qu'un conteneur réserve d'office : elle sert au placement, pas à une limite haute.",
  limit: "Le plafond qu'un conteneur ne peut pas dépasser : au-delà, il est bridé (CPU) ou tué (mémoire).",
  heap: "La zone de mémoire où une machine virtuelle comme la JVM alloue ses objets, gérée par un ramasse-miettes.",
  'working set': "La mémoire réellement utilisée par un conteneur à un instant donné, mesurée par le noyau, pas annoncée par l'application.",
  "dead man's switch": "Un interrupteur d'homme mort : une alerte qui doit rester active en permanence, dont le silence signale la panne du système d'alerte lui-même.",
  receiver: "Le récepteur : la destination d'une alerte dans Alertmanager (un canal de notification, un webhook, ou l'absence de destination).",
  pull: "Un modèle de collecte où l'observateur va chercher la donnée chez la cible, à son rythme (c'est le modèle de Prometheus).",
  push: "Un modèle de collecte où la cible envoie elle-même sa donnée vers un collecteur, sans attendre d'être interrogée.",
  cardinalité: "Le nombre de combinaisons distinctes que peuvent prendre les étiquettes d'une métrique : une cardinalité trop haute épuise la mémoire du serveur de métriques.",
  'N+1': "Le défaut de charger une liste puis, pour chaque élément, une requête séparée vers la base : une requête prévue en devient N+1.",
  'kube-proxy': "Le composant qui traduit un Service Kubernetes en règles de redirection réseau, une par connexion, pas par requête.",
  pod: "La plus petite unité déployable de Kubernetes : un ou plusieurs conteneurs qui partagent réseau et stockage.",
  GitOps: "Une pratique où l'état désiré d'un système vit dans un dépôt git, et où un agent applique en continu ce que le dépôt décrit."
}
